# .theme-check.yml
extends: "theme-check:recommended"

# You can tune rules later as you learn.
ThemeAssetSize:
  enabled: false  # keep off for now; turn on later if you want strict asset sizes
AssetPreload:
  enabled: true
SchemaTranslations:
  enabled: true
LiquidTag:
  enabled: true
