name: Shopify Theme Check

on:
  pull_request:
    branches: [ main ]  # run on PRs targeting main

jobs:
  theme_check:
    name: Shopify Theme Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install theme-check
        run: gem install theme-check

      - name: Run theme-check
        run: theme-check
